# Task B4:
Perform the morphological operations in Part A again but by coding.

In [1]:
import numpy as np

In [8]:
image = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 1, 1, 0],
    [0, 0, 1, 1, 1, 1, 0, 0],
    [0, 1, 1, 1, 1, 0, 0, 0],
    [0, 1, 1, 1, 1, 0, 0, 0],
    [0, 1, 1, 1, 0, 0, 0, 0],
    [0, 0, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0]
])

structuring_element = np.array([
    [0, 1, 0],
    [1, 1, 1],
    [0, 1, 0]
])

padded_image = np.pad(image, pad_width=1,constant_values=0)

In [ ]:
def erosion(image,se):
    output=np.zeros_like(image)
    for i in range(1, image.shape[0]-1):
        for j in range(1, image.shape[1]-1):
            window=image[i-1:i+2, j-1:j+2]
            if np.all(window[se == 1] == 1):
                output[i, j] = 1
    return output

def dilation(image,se):
    output=np.zeros_like(image)
    for i in range(1, image.shape[0]-1):
        for j in range(1, image.shape[1]-1):
            window=image[i-1:i+2, j-1:j+2]
            if np.any(window[se == 1] == 1):
                output[i, j] = 1
    return output

In [12]:
eroded_image = erosion(padded_image,structuring_element)
print(eroded_image[1:-1, 1:-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [11]:
dilated_image = dilation(padded_image,structuring_element)
print(dilated_image[1:-1, 1:-1])

[[0 0 0 0 1 1 1 0]
 [0 0 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 0 0]
 [1 1 1 1 1 0 0 0]
 [0 1 1 1 1 0 0 0]
 [0 0 1 1 0 0 0 0]]


In [17]:
def opening(image,se):
    output = erosion(image,se)
    output = dilation(output,se)
    return output

def closing(image,se):
    output = dilation(image,se)
    output = erosion(output,se)
    return output

In [15]:
opened_image = opening(padded_image,structuring_element)
print(opened_image[1:-1, 1:-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 1 1 1 1 0 0]
 [0 1 1 1 1 0 0 0]
 [0 1 1 1 1 0 0 0]
 [0 1 1 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [18]:
closed_image = closing(padded_image,structuring_element)
print(closed_image[1:-1, 1:-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 0]
 [0 0 1 1 1 1 0 0]
 [0 1 1 1 1 0 0 0]
 [0 1 1 1 1 0 0 0]
 [0 1 1 1 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
